[package]
name = "xiapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xiapi-sys = {git = "https://github.com/Ximea-GmbH/xiapi-sys.git"}

[dev-dependencies]
serial_test = "0.5.1"
approx = "0.5.0"